/**
 * 系統常數定義
 */

// 工作階段常數
export const SESSION_CONSTANTS = {
  ID_LENGTH: 6,
  // TIMEOUT 和 CLEANUP_INTERVAL 從 SERVER_CONFIG 讀取
};

// 分享代碼常數
export const SHARE_CODE_CONSTANTS = {
  LENGTH: 6,
  BASE_LENGTH: 5, // 5位數字
  CHECKSUM_LENGTH: 1, // 1位校驗碼
  // TIMEOUT 從 SERVER_CONFIG 讀取
};

// 客戶端常數
export const CLIENT_CONSTANTS = {
  PREFIX: "D",
  // HEARTBEAT_INTERVAL 和 HEARTBEAT_TIMEOUT 從 SERVER_CONFIG 讀取
};

// 實驗ID常數
export const EXPERIMENT_ID_CONSTANTS = {
  LENGTH: 6,
  // VALID_CREATE_CODE 從 SERVER_CONFIG 讀取
};

// 客戶端角色
export const ROLE = {
  OPERATOR: "operator",
  VIEWER: "viewer",
};

// 公開頻道常數
export const CHANNEL_CONSTANTS = {
  PREFIX: "__CH_",
  VALID_NAMES: ["A", "B", "C"],
};

// HTTP響應碼
export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_ERROR: 500,
};

// 錯誤碼
export const ERROR_CODES = {
  INVALID_REQUEST: "INVALID_REQUEST",
  INVALID_SESSION_ID: "INVALID_SESSION_ID",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  INVALID_SHARE_CODE: "INVALID_SHARE_CODE",
  SHARE_CODE_EXPIRED: "SHARE_CODE_EXPIRED",
  SHARE_CODE_NOT_FOUND: "SHARE_CODE_NOT_FOUND",
  INVALID_CREATE_CODE: "INVALID_CREATE_CODE",
  CLIENT_NOT_FOUND: "CLIENT_NOT_FOUND",
  INVALID_EXPERIMENT_ID: "INVALID_EXPERIMENT_ID",
  DATABASE_ERROR: "DATABASE_ERROR",
};
