/**
 * Constants 統一入口
 * 集中管理所有常數，簡化 import 路徑
 */

import {
  RECORD_TYPES,
  RECORD_TYPE_LABELS,
  GESTURE_ATTEMPT_TYPES,
  GESTURE_ATTEMPT_TYPE_LABELS,
} from "./record-types-constants.js";

import {
  SYNC_EVENTS,
  SYNC_DATA_TYPES,
  getEventName,
} from "./sync-events-constants.js";

import { RECORD_SOURCES } from "./record-source-constants.js";

import { ACTION_IDS, ACTION_BUTTONS, ACTION_CONSTANTS } from "./action-constants.js";
import { POWER_BUTTON_STATES } from "./power-constants.js";
import {
  EXPERIMENT_ACTION_HANDLER_EVENTS,
  EXPERIMENT_ACTION_HANDLER_DEFAULTS,
  EXPERIMENT_FLOW_STATE,
  EXPERIMENT_FLOW_EVENTS,
  EXPERIMENT_FLOW_DOM_EVENTS,
  EXPERIMENT_COMBINATION_EVENTS,
  EXPERIMENT_HUB_CONSTANTS,
} from "./experiment-constants.js";
import {
  SYNC_MANAGER_CONSTANTS,
  SYNC_ROLE_CONFIG,
  SYNC_STATUS_CONFIG,
  SYNC_PAGE_CONFIG,
  SYNC_ROLE_TEXTS,
  SYNC_MODE_TEXTS,
  SYNC_STATUS_TEXTS,
  SYNC_PAGE_LIST,
  SYNC_SESSION_STORAGE_KEYS,
  SYNC_CLIENT_CONSTANTS,
  getSyncRoleText,
  addSyncRoleText,
  getSyncStatusText,
  addSyncStatusText,
  getSyncPageName,
  getSyncPagePath,
  addSyncPage,
} from "./sync-constants.js";
import { API_ENDPOINTS } from "./api-constants.js";

export {
  RECORD_TYPES,
  RECORD_TYPE_LABELS,
  GESTURE_ATTEMPT_TYPES,
  GESTURE_ATTEMPT_TYPE_LABELS,
  SYNC_EVENTS,
  SYNC_DATA_TYPES,
  getEventName,
  RECORD_SOURCES,
  ACTION_IDS,
  ACTION_BUTTONS,
  ACTION_CONSTANTS,
  POWER_BUTTON_STATES,
  EXPERIMENT_ACTION_HANDLER_EVENTS,
  EXPERIMENT_ACTION_HANDLER_DEFAULTS,
  EXPERIMENT_FLOW_STATE,
  EXPERIMENT_FLOW_EVENTS,
  EXPERIMENT_FLOW_DOM_EVENTS,
  EXPERIMENT_COMBINATION_EVENTS,
  EXPERIMENT_HUB_CONSTANTS,
  SYNC_MANAGER_CONSTANTS,
  SYNC_ROLE_CONFIG,
  SYNC_STATUS_CONFIG,
  SYNC_PAGE_CONFIG,
  SYNC_ROLE_TEXTS,
  SYNC_MODE_TEXTS,
  SYNC_STATUS_TEXTS,
  SYNC_PAGE_LIST,
  SYNC_SESSION_STORAGE_KEYS,
  SYNC_CLIENT_CONSTANTS,
  getSyncRoleText,
  addSyncRoleText,
  getSyncStatusText,
  addSyncStatusText,
  getSyncPageName,
  getSyncPagePath,
  addSyncPage,
  API_ENDPOINTS,
};

